
# [defaultNamespace]: The namespace to use for emotes if none is specified
# [defaultFolder]: The default folder-path textures are in (assets/namespace/textures/defaultFolder)
# [defaultFont]: The font emotes will use if none is specified (GIFs use their ID)
# [defaultHeight]: The height emotes and gifs will use if none is specified
# [defaultAscent]: The ascent emotes and gifs will use if none is specified
# [requirePermission]: Should emotes and gifs require permissions? Permission can be per emote, or font (emojy.emote/font/gif)
# [generateResourcePack]: Should an assets style folder generate with needed fonts and images?
# [debug]: Prints out error msg for resourcepack generation
# [filterListByPermission]: If /emojy list only shows emotes the player has permission to use
defaultNamespace: "emotes"
defaultFolder: "emotes"
defaultFont: "emotes"
defaultHeight: 8
defaultAscent: 8
requirePermission: true
generateResourcePack: true
debug: true
listType: BOOK

# [id]: The id of your emote, used for replacing :id:
# [texture]: The path to your textures image (defaultNamespace:defaultFolder/id.png)
# [font]: The font your emote should use
# [height]: The height of your emote
# [ascent]: The ascent of your emote
emotes:
  - id: pog
    texture: "emotes:emotes/pog.png"
    font: "emotes"
    height: 8
    ascent: 8

# [id]: The id of your gif, used for replacing :id:
# [frameCount]: The amount of frames your GIF should have, 0 or below uses the gifs actual framecount
# [framePath]: The path to your GIFs images, unlike emotes this does not include the pngs
# [ascent]: The height of your gif
# [height]: The ascent of your gif
gifs:
  - id: test
    frameCount: 0
    framePath: "emotes:gifs/"
    ascent: 8
    height: 8
